# Form implementation generated from reading ui file 'c:\ProjectPython\gui\Student.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_stdmain(object):
    def setupUi(self, stdmain):
        stdmain.setObjectName("stdmain")
        stdmain.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=stdmain)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Last = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Last.setGeometry(QtCore.QRect(40, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_Last.setFont(font)
        self.lbl_Last.setObjectName("lbl_Last")
        self.lbl_Name = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Name.setGeometry(QtCore.QRect(40, 50, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_Name.setFont(font)
        self.lbl_Name.setObjectName("lbl_Name")
        self.lbl_Code = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Code.setGeometry(QtCore.QRect(40, 190, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_Code.setFont(font)
        self.lbl_Code.setObjectName("lbl_Code")
        self.txt_Name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_Name.setGeometry(QtCore.QRect(190, 70, 221, 41))
        self.txt_Name.setText("")
        self.txt_Name.setObjectName("txt_Name")
        self.txt_Last = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_Last.setGeometry(QtCore.QRect(190, 130, 221, 41))
        self.txt_Last.setObjectName("txt_Last")
        self.txt_Code = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_Code.setGeometry(QtCore.QRect(190, 190, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txt_Code.setFont(font)
        self.txt_Code.setObjectName("txt_Code")
        self.btnCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(160, 260, 101, 41))
        self.btnCancel.setObjectName("btnCancel")
        self.btnSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(300, 260, 121, 41))
        self.btnSave.setObjectName("btnSave")
        self.txt = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txt.setGeometry(QtCore.QRect(430, 30, 331, 411))
        self.txt.setObjectName("txt")
        stdmain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=stdmain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        stdmain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=stdmain)
        self.statusbar.setObjectName("statusbar")
        stdmain.setStatusBar(self.statusbar)
        self.lbl_Last.setBuddy(self.txt_Last)
        self.lbl_Name.setBuddy(self.txt_Name)
        self.lbl_Code.setBuddy(self.txt_Code)

        self.retranslateUi(stdmain)
        self.btnCancel.clicked.connect(self.txt_Name.clear) # type: ignore
        self.btnCancel.clicked.connect(self.txt_Last.clear) # type: ignore
        self.btnCancel.clicked.connect(self.txt_Code.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(stdmain)

    def retranslateUi(self, stdmain):
        _translate = QtCore.QCoreApplication.translate
        stdmain.setWindowTitle(_translate("stdmain", "โปรแกรทบันทึกข้อมูลนักเรียน"))
        self.lbl_Last.setText(_translate("stdmain", "LastName"))
        self.lbl_Name.setText(_translate("stdmain", "Firstname"))
        self.lbl_Code.setText(_translate("stdmain", "StudentID"))
        self.btnCancel.setText(_translate("stdmain", "CANCEL"))
        self.btnSave.setText(_translate("stdmain", "SAVE"))
